/* CVS $Id: $ */
package org.doremus.ontology;
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;

/**
 * Vocabulary definitions from https://raw.githubusercontent.com/DOREMUS-ANR/doremus-ontology/master/frbroo.owl
 * @author Auto-generated by schemagen on 23 ago 2017 14:12
 */
public class FRBROO {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://erlangen-crm.org/efrbroo/";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "EFRBRoo 121016 / FRBRoo 1.0.2 / ECRM current / CIDOC-CRM 5.0.4";

    public static final ObjectProperty CLP104_subject_to = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLP104_subject_to" );

    public static final ObjectProperty CLP104i_applies_to = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLP104i_applies_to" );

    public static final ObjectProperty CLP105_right_held_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLP105_right_held_by" );

    public static final ObjectProperty CLP105i_right_on = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLP105i_right_on" );

    public static final ObjectProperty CLP2_should_have_type = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLP2_should_have_type" );

    public static final ObjectProperty CLP2i_should_be_type_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLP2i_should_be_type_of" );

    public static final ObjectProperty CLP43_should_have_dimension = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLP43_should_have_dimension" );

    public static final ObjectProperty CLP43i_should_be_dimension_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLP43i_should_be_dimension_of" );

    public static final ObjectProperty CLP45_should_consist_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLP45_should_consist_of" );

    public static final ObjectProperty CLP45i_should_be_incorporated_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLP45i_should_be_incorporated_in" );

    public static final ObjectProperty CLP46_should_be_composed_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLP46_should_be_composed_of" );

    public static final ObjectProperty CLP46i_may_form_part_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLP46i_may_form_part_of" );

    public static final ObjectProperty CLR6_should_carry = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLR6_should_carry" );

    public static final ObjectProperty CLR6i_should_be_carried_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/CLR6i_should_be_carried_by" );

    public static final ObjectProperty R10_has_member = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R10_has_member" );

    public static final ObjectProperty R10i_is_member_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R10i_is_member_of" );

    public static final ObjectProperty R11_has_issuing_rule = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R11_has_issuing_rule" );

    public static final ObjectProperty R11i_is_issuing_rule_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R11i_is_issuing_rule_of" );

    public static final ObjectProperty R12_is_realised_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R12_is_realised_in" );

    public static final ObjectProperty R12i_realises = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R12i_realises" );

    public static final ObjectProperty R13_is_realised_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R13_is_realised_in" );

    public static final ObjectProperty R13i_realises = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R13i_realises" );

    public static final ObjectProperty R15_has_fragment = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R15_has_fragment" );

    public static final ObjectProperty R15i_is_fragment_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R15i_is_fragment_of" );

    public static final ObjectProperty R16_initiated = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R16_initiated" );

    public static final ObjectProperty R16i_was_initiated_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R16i_was_initiated_by" );

    public static final ObjectProperty R17_created = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R17_created" );

    public static final ObjectProperty R17i_was_created_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R17i_was_created_by" );

    public static final ObjectProperty R18_created = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R18_created" );

    public static final ObjectProperty R18i_was_created_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R18i_was_created_by" );

    public static final ObjectProperty R19_created_a_realisation_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R19_created_a_realisation_of" );

    public static final ObjectProperty R19i_was_realised_through = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R19i_was_realised_through" );

    public static final ObjectProperty R1_is_logical_successor_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R1_is_logical_successor_of" );

    public static final ObjectProperty R1i_has_successor = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R1i_has_successor" );

    public static final ObjectProperty R20_recorded = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R20_recorded" );

    public static final ObjectProperty R20i_was_recorded_through = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R20i_was_recorded_through" );

    public static final ObjectProperty R21_created = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R21_created" );

    public static final ObjectProperty R21i_was_created_through = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R21i_was_created_through" );

    public static final ObjectProperty R22_created_a_realisation_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R22_created_a_realisation_of" );

    public static final ObjectProperty R22i_was_realised_through = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R22i_was_realised_through" );

    public static final ObjectProperty R23_created_a_realisation_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R23_created_a_realisation_of" );

    public static final ObjectProperty R23i_was_realised_through = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R23i_was_realised_through" );

    public static final ObjectProperty R24_created = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R24_created" );

    public static final ObjectProperty R24i_was_created_through = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R24i_was_created_through" );

    public static final ObjectProperty R25_performed = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R25_performed" );

    public static final ObjectProperty R25i_was_performed_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R25i_was_performed_in" );

    public static final ObjectProperty R26_produced_things_of_type = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R26_produced_things_of_type" );

    public static final ObjectProperty R26i_was_produced_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R26i_was_produced_by" );

    public static final ObjectProperty R27_used_as_source_material = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R27_used_as_source_material" );

    public static final ObjectProperty R27i_was_used_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R27i_was_used_by" );

    public static final ObjectProperty R28_produced = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R28_produced" );

    public static final ObjectProperty R28i_was_produced_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R28i_was_produced_by" );

    public static final ObjectProperty R29_reproduced = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R29_reproduced" );

    public static final ObjectProperty R29i_was_reproduced_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R29i_was_reproduced_by" );

    public static final ObjectProperty R2_is_derivative_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R2_is_derivative_of" );

    public static final ObjectProperty R2i_has_derivative = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R2i_has_derivative" );

    public static final ObjectProperty R30_produced = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R30_produced" );

    public static final ObjectProperty R30i_was_produced_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R30i_was_produced_by" );

    public static final ObjectProperty R31_is_reproduction_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R31_is_reproduction_of" );

    public static final ObjectProperty R31i_has_reproduction = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R31i_has_reproduction" );

    public static final ObjectProperty R32_is_warranted_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R32_is_warranted_by" );

    public static final ObjectProperty R32i_warrants = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R32i_warrants" );

    public static final ObjectProperty R34_has_validity_period = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R34_has_validity_period" );

    public static final ObjectProperty R34i_is_validity_period_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R34i_is_validity_period_of" );

    public static final ObjectProperty R35_is_specified_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R35_is_specified_by" );

    public static final ObjectProperty R35i_specifies = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R35i_specifies" );

    public static final ObjectProperty R36_uses_script_conversion = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R36_uses_script_conversion" );

    public static final ObjectProperty R36i_is_script_conversion_used_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R36i_is_script_conversion_used_in" );

    public static final ObjectProperty R37_states_as_nomen = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R37_states_as_nomen" );

    public static final ObjectProperty R37i_is_stated_as_nomen_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R37i_is_stated_as_nomen_in" );

    public static final ObjectProperty R38_refers_to_thema = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R38_refers_to_thema" );

    public static final ObjectProperty R38i_is_thema_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R38i_is_thema_of" );

    public static final ObjectProperty R39_is_intended_for = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R39_is_intended_for" );

    public static final ObjectProperty R39i_is_target_audience_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R39i_is_target_audience_in" );

    public static final ObjectProperty R3_is_realised_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R3_is_realised_in" );

    public static final ObjectProperty R3i_realises = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R3i_realises" );

    public static final ObjectProperty R40_has_representative_expression = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R40_has_representative_expression" );

    public static final ObjectProperty R40i_is_representative_expression_for = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R40i_is_representative_expression_for" );

    public static final ObjectProperty R41_has_representative_manifestation_product_type = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R41_has_representative_manifestation_product_type" );

    public static final ObjectProperty R41i_is_representative_manifestation_product_type_for = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R41i_is_representative_manifestation_product_type_for" );

    public static final ObjectProperty R42_is_representative_manifestation_singleton_for = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R42_is_representative_manifestation_singleton_for" );

    public static final ObjectProperty R42i_has_representative_manifestation_singleton = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R42i_has_representative_manifestation_singleton" );

    public static final ObjectProperty R43_carried_out_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R43_carried_out_by" );

    public static final ObjectProperty R43i_performed = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R43i_performed" );

    public static final ObjectProperty R44_carried_out_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R44_carried_out_by" );

    public static final ObjectProperty R44i_performed = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R44i_performed" );

    public static final ObjectProperty R45_assigned_to = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R45_assigned_to" );

    public static final ObjectProperty R45i_was_assigned_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R45i_was_assigned_by" );

    public static final ObjectProperty R46_assigned = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R46_assigned" );

    public static final ObjectProperty R46i_was_assigned_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R46i_was_assigned_by" );

    public static final ObjectProperty R48_assigned_to = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R48_assigned_to" );

    public static final ObjectProperty R48i_was_assigned_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R48i_was_assigned_by" );

    public static final ObjectProperty R49_assigned = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R49_assigned" );

    public static final ObjectProperty R49i_was_assigned_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R49i_was_assigned_by" );

    public static final ObjectProperty R4_carriers_provided_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R4_carriers_provided_by" );

    public static final ObjectProperty R4i_comprises_carriers_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R4i_comprises_carriers_of" );

    public static final ObjectProperty R50_assigned_to = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R50_assigned_to" );

    public static final ObjectProperty R50i_was_assigned_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R50i_was_assigned_by" );

    public static final ObjectProperty R51_assigned = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R51_assigned" );

    public static final ObjectProperty R51i_was_assigned_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R51i_was_assigned_by" );

    public static final ObjectProperty R52_used_rule = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R52_used_rule" );

    public static final ObjectProperty R52i_was_the_rule_used_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R52i_was_the_rule_used_in" );

    public static final ObjectProperty R53_assigned = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R53_assigned" );

    public static final ObjectProperty R53i_was_assigned_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R53i_was_assigned_by" );

    public static final ObjectProperty R54_has_nomen_language = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R54_has_nomen_language" );

    public static final ObjectProperty R54i_is_language_of_nomen_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R54i_is_language_of_nomen_in" );

    public static final ObjectProperty R55_has_nomen_form = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R55_has_nomen_form" );

    public static final ObjectProperty R55i_is_nomen_form_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R55i_is_nomen_form_in" );

    public static final ObjectProperty R56_has_related_use = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R56_has_related_use" );

    public static final ObjectProperty R56i_is_related_use_for = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R56i_is_related_use_for" );

    public static final ObjectProperty R57_is_based_on = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R57_is_based_on" );

    public static final ObjectProperty R57i_is_basis_for = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R57i_is_basis_for" );

    public static final ObjectProperty R58_has_fictional_member = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R58_has_fictional_member" );

    public static final ObjectProperty R58i_is_fictional_member_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R58i_is_fictional_member_of" );

    public static final ObjectProperty R59_had_typical_subject = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R59_had_typical_subject" );

    public static final ObjectProperty R59i_was_typical_subject_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R59i_was_typical_subject_of" );

    public static final ObjectProperty R5_has_component = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R5_has_component" );

    public static final ObjectProperty R5i_is_component_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R5i_is_component_of" );

    public static final ObjectProperty R60_used_to_use_language = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R60_used_to_use_language" );

    public static final ObjectProperty R60i_was_language_used_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R60i_was_language_used_by" );

    public static final ObjectProperty R61_occurred_in_kind_of_context = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R61_occurred_in_kind_of_context" );

    public static final ObjectProperty R61i_was_kind_of_context_for = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R61i_was_kind_of_context_for" );

    public static final ObjectProperty R62_was_used_for_membership_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R62_was_used_for_membership_in" );

    public static final ObjectProperty R62i_was_context_for = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R62i_was_context_for" );

    public static final ObjectProperty R63_named = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R63_named" );

    public static final ObjectProperty R63i_was_named_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R63i_was_named_by" );

    public static final ObjectProperty R64_used_name = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R64_used_name" );

    public static final ObjectProperty R64i_was_name_used_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R64i_was_name_used_by" );

    public static final ObjectProperty R65_recorded_aspects_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R65_recorded_aspects_of" );

    public static final ObjectProperty R65i_had_aspects_recorded_through = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R65i_had_aspects_recorded_through" );

    public static final ObjectProperty R66_included_performed_version_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R66_included_performed_version_of" );

    public static final ObjectProperty R66i = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R66i" );

    public static final ObjectProperty R6_carries = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R6_carries" );

    public static final ObjectProperty R6i_is_carried_by = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R6i_is_carried_by" );

    public static final ObjectProperty R7_is_example_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R7_is_example_of" );

    public static final ObjectProperty R7i_has_example = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R7i_has_example" );

    public static final ObjectProperty R8_consists_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R8_consists_of" );

    public static final ObjectProperty R8i_forms_part_of = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R8i_forms_part_of" );

    public static final ObjectProperty R9_is_realised_in = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R9_is_realised_in" );

    public static final ObjectProperty R9i_realises = m_model.createObjectProperty( "http://erlangen-crm.org/efrbroo/R9i_realises" );

    public static final DatatypeProperty CLP57_should_have_number_of_parts = m_model.createDatatypeProperty( "http://erlangen-crm.org/efrbroo/CLP57_should_have_number_of_parts" );

    public static final DatatypeProperty R33_has_content = m_model.createDatatypeProperty( "http://erlangen-crm.org/efrbroo/R33_has_content" );

    public static final OntClass F10_Person = m_model.createClass( "http://erlangen-crm.org/efrbroo/F10_Person" );

    public static final OntClass F11_Corporate_Body = m_model.createClass( "http://erlangen-crm.org/efrbroo/F11_Corporate_Body" );

    public static final OntClass F12_Nomen = m_model.createClass( "http://erlangen-crm.org/efrbroo/F12_Nomen" );

    public static final OntClass F13_Identifier = m_model.createClass( "http://erlangen-crm.org/efrbroo/F13_Identifier" );

    public static final OntClass F14_Individual_Work = m_model.createClass( "http://erlangen-crm.org/efrbroo/F14_Individual_Work" );

    public static final OntClass F15_Complex_Work = m_model.createClass( "http://erlangen-crm.org/efrbroo/F15_Complex_Work" );

    public static final OntClass F16_Container_Work = m_model.createClass( "http://erlangen-crm.org/efrbroo/F16_Container_Work" );

    public static final OntClass F17_Aggregation_Work = m_model.createClass( "http://erlangen-crm.org/efrbroo/F17_Aggregation_Work" );

    public static final OntClass F18_Serial_Work = m_model.createClass( "http://erlangen-crm.org/efrbroo/F18_Serial_Work" );

    public static final OntClass F19_Publication_Work = m_model.createClass( "http://erlangen-crm.org/efrbroo/F19_Publication_Work" );

    public static final OntClass F1_Work = m_model.createClass( "http://erlangen-crm.org/efrbroo/F1_Work" );

    public static final OntClass F20_Performance_Work = m_model.createClass( "http://erlangen-crm.org/efrbroo/F20_Performance_Work" );

    public static final OntClass F21_Recording_Work = m_model.createClass( "http://erlangen-crm.org/efrbroo/F21_Recording_Work" );

    public static final OntClass F22_Self_Contained_Expression = m_model.createClass( "http://erlangen-crm.org/efrbroo/F22_Self-Contained_Expression" );

    public static final OntClass F23_Expression_Fragment = m_model.createClass( "http://erlangen-crm.org/efrbroo/F23_Expression_Fragment" );

    public static final OntClass F24_Publication_Expression = m_model.createClass( "http://erlangen-crm.org/efrbroo/F24_Publication_Expression" );

    public static final OntClass F25_Performance_Plan = m_model.createClass( "http://erlangen-crm.org/efrbroo/F25_Performance_Plan" );

    public static final OntClass F26_Recording = m_model.createClass( "http://erlangen-crm.org/efrbroo/F26_Recording" );

    public static final OntClass F27_Work_Conception = m_model.createClass( "http://erlangen-crm.org/efrbroo/F27_Work_Conception" );

    public static final OntClass F28_Expression_Creation = m_model.createClass( "http://erlangen-crm.org/efrbroo/F28_Expression_Creation" );

    public static final OntClass F29_Recording_Event = m_model.createClass( "http://erlangen-crm.org/efrbroo/F29_Recording_Event" );

    public static final OntClass F2_Expression = m_model.createClass( "http://erlangen-crm.org/efrbroo/F2_Expression" );

    public static final OntClass F30_Publication_Event = m_model.createClass( "http://erlangen-crm.org/efrbroo/F30_Publication_Event" );

    public static final OntClass F31_Performance = m_model.createClass( "http://erlangen-crm.org/efrbroo/F31_Performance" );

    public static final OntClass F32_Carrier_Production_Event = m_model.createClass( "http://erlangen-crm.org/efrbroo/F32_Carrier_Production_Event" );

    public static final OntClass F33_Reproduction_Event = m_model.createClass( "http://erlangen-crm.org/efrbroo/F33_Reproduction_Event" );

    public static final OntClass F34_KOS = m_model.createClass( "http://erlangen-crm.org/efrbroo/F34_KOS" );

    public static final OntClass F35_Nomen_Use_Statement = m_model.createClass( "http://erlangen-crm.org/efrbroo/F35_Nomen_Use_Statement" );

    public static final OntClass F36_Script_Conversion = m_model.createClass( "http://erlangen-crm.org/efrbroo/F36_Script_Conversion" );

    public static final OntClass F38_Character = m_model.createClass( "http://erlangen-crm.org/efrbroo/F38_Character" );

    public static final OntClass F39_Family = m_model.createClass( "http://erlangen-crm.org/efrbroo/F39_Family" );

    public static final OntClass F3_Manifestation_Product_Type = m_model.createClass( "http://erlangen-crm.org/efrbroo/F3_Manifestation_Product_Type" );

    public static final OntClass F40_Identifier_Assignment = m_model.createClass( "http://erlangen-crm.org/efrbroo/F40_Identifier_Assignment" );

    public static final OntClass F41_Representative_Manifestation_Assignment = m_model.createClass( "http://erlangen-crm.org/efrbroo/F41_Representative_Manifestation_Assignment" );

    public static final OntClass F42_Representative_Expression_Assignment = m_model.createClass( "http://erlangen-crm.org/efrbroo/F42_Representative_Expression_Assignment" );

    public static final OntClass F43_Identifier_Rule = m_model.createClass( "http://erlangen-crm.org/efrbroo/F43_Identifier_Rule" );

    public static final OntClass F44_Bibliographic_Agency = m_model.createClass( "http://erlangen-crm.org/efrbroo/F44_Bibliographic_Agency" );

    public static final OntClass F4_Manifestation_Singleton = m_model.createClass( "http://erlangen-crm.org/efrbroo/F4_Manifestation_Singleton" );

    public static final OntClass F50_Controlled_Access_Point = m_model.createClass( "http://erlangen-crm.org/efrbroo/F50_Controlled_Access_Point" );

    public static final OntClass F51_Pursuit = m_model.createClass( "http://erlangen-crm.org/efrbroo/F51_Pursuit" );

    public static final OntClass F52_Name_Use_Activity = m_model.createClass( "http://erlangen-crm.org/efrbroo/F52_Name_Use_Activity" );

    public static final OntClass F53_Material_Copy = m_model.createClass( "http://erlangen-crm.org/efrbroo/F53_Material_Copy" );

    public static final OntClass F54_Utilised_Information_Carrier = m_model.createClass( "http://erlangen-crm.org/efrbroo/F54_Utilised_Information_Carrier" );

    public static final OntClass F5_Item = m_model.createClass( "http://erlangen-crm.org/efrbroo/F5_Item" );

    public static final OntClass F6_Concept = m_model.createClass( "http://erlangen-crm.org/efrbroo/F6_Concept" );

    public static final OntClass F7_Object = m_model.createClass( "http://erlangen-crm.org/efrbroo/F7_Object" );

    public static final OntClass F8_Event = m_model.createClass( "http://erlangen-crm.org/efrbroo/F8_Event" );

    public static final OntClass F9_Place = m_model.createClass( "http://erlangen-crm.org/efrbroo/F9_Place" );

}
